### ISSUE TITLE
What are worse case scenarios

### ISSUE THREAD

**Issue by okwme** [tendermint/spn#102]
> what scenarios that the registry might cause and what could be done to mitigate and avoid it.
>     * What happens if there are fundamental disagreements about the chain.
>     * What happens if the chains security is compromised
>     * etc..

**Comment by fadeev** [comment]
One of the challenges of phase 0 is to assign chain names to existing blockchains. There will be a multisig account (let’s call it “maintainer”) responsible for this, but there may be disagreements. The way we can prevent this is by requiring chains to vote for an account that will be granted rights to manage the chain’s name on CNS.

For example, the community of Foobar Hub wants to register foobar on CNS. The first thing they do is vote on a (most likely, multisig) account that will own the name on CNS. Voting happens using the chain’s native governance mechanisms. After the voting said account sends a transaction to CNS with the proof of voting (most likely a URL) so that the “maintainer” of CNS has grounds to assign the name. This process occurs only during phase 0, the objective of which is to correctly assign chain names to existing blockchains.

**Comment by lubtd** [comment]
Moved to https://github.com/tendermint/cns
