### ISSUE TITLE
What are the implications of chain upgrades

### ISSUE THREAD

**Issue by okwme** [tendermint/spn#103]
>  the notion that hard forks require a new chain id might be challenged in the future with some ongoing work in Tendermint looking to improve upgrade tooling. It's feasible for different application binaries to run with the same chain id and be separated by height only. This may mean that a single network doesn’t need to own a set of chain-id’s but just one

**Comment by fadeev** [comment]
We may need to differentiate between a unique name assigned to a blockchain on CNS and an equally unique chain ID, computed from chain information stored on CNS.

If information about Cosmos Hub itself would’ve been stored on CNS, it would have a unique name `cosmoshub` and a `version` with the value `3`. Computed chain ID would thus be `cosmoshub-3`.

If at any point in time in the future software changes so that the requirement for chain IDs is to have an emoji as a first character, then the name will still be `cosmoshub`, `version: 25` and `emoji: 🪐` and computed chain ID: `🪐-cosmoshub-25`.

**Comment by lubtd** [comment]
Moved to https://github.com/tendermint/cns
