### ISSUE TITLE
Inconsistent naming: ProposalState and ProposalStatus

### ISSUE THREAD

**Issue by dshulyak** [tendermint/spn#139]

**Comment by lubtd** [comment]
Proposal status determine if the proposal has been approved: `APPROVED|REJECTED|PENDING`
Proposal state is referring to what is "dynamic" for the proposal, at the end we only have the status as dynamic. Before, we planned to have a voting process to approve a proposal (instead of just the coordinator approving them) and so the Proposal State would have kept this vote process state.

We will stay with the coordinator approval process for the time being and so we will just drop Proposal State

**Comment by dshulyak** [comment]
My bad, i didn't notice that status is a part of the state
