### ISSUE TITLE
refund the user if the chain was not launched

### ISSUE THREAD

**Issue by Pantani** [tendermint/spn#389]
**Is your feature request related to a problem? Please describe.**

The user can buy vouchers, but the chain has the chance not to be launched.

**Describe the solution you'd like**

We could add a time lock for the voucher to refund part of the money to the user if the coordinator did not launch the chain.

**Comment by lubtd** [comment]
Thanks for raising this.

The refund will always be implemented at the application-layer. The module that sells the vouchers.

In the example of `fundraising`, we discussed with the `fundraising` team. A solution through vesting and governance will be implemented for this use case.

I close the issue since there is no general solution but specific ones depending on the application layer
