### ISSUE TITLE
disable use of tunneled peers on mainnet

### ISSUE THREAD

**Issue by ilgooz** [tendermint/spn#508]
Disable this option for mainnets for extra security.

https://github.com/tendermint/spn/blob/99fe22b/proto/launch/genesis_validator.proto#L23

**Comment by lubtd** [comment]
Can we get more details why is it a security matter?

On-chain `mainnet` represents chains where token allocations are defined from campaign shares. But by design, a real mainnet or a blockchain with tokens representing real monetary value can also be launched directly through the `launch` module.
Therefore, if tunneled peer is a security concern for real blockchain outside of experimentation, I would advocate removing it totally from the Genesis Validator Peer information and keeping it only as metadata that is read for experimentation only.

We can also consider that is is it can be something managed in the front-end, we prevent setting this value for the validator when a real chain is concerned

**Comment by lubtd** [comment]
I don't see specific justification to use `High-Priority` tag regarding the rest of the backlog

**Comment by lubtd** [comment]
Closing as it is a matter of the chain source to enable or not tunneled peers
