### ISSUE TITLE
Create a query to get the maximum number of shares

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#653]
The maximum of share is set to `DefaultTotalShareNumber = 100000` in `campaign/types/shares.go`

Since it is hardcoded we should provide a query under `campaign` namespace to fetch these values

I think we can also rename `DefaultTotalShareNumber` into `TotalShareNumber` and possibly move it in `pkg/types/constant.go` since it's quite an important value in the chain as a whole

**Comment by lubtd** [comment]
> Do you mean to have this as a a default value for a param in the campaign module? Or to just add a query that returns this constant value?

Nope keeping a constant and having a query that returns this constant. We should not have this value has a param as it should not be modified (a change of this max would imply all campaigns must update their allocated shares otherwise the shares get diluted)
This will be a constant, we can eventually have different values depending on the network, hence the query

**Comment by aljo242** [comment]
I think having this set up in this way could lead to the scenario where node operators could edit this constant value, then rebuild their binary and return an incorrect value for this query.  Since the value is not stored in the app state (db), there is no check being done between nodes, meaning they could all have different values.

I suggest we set this value in the KVStore, but not as a param.  This way it is included in the AppHash, so validators who change this value, will have an Consensus error.  Not setting it as a param means we can also not expose any way for the value to be edited programatically. 


Thoughts?

**Comment by lubtd** [comment]
> I think having this set up in this way could lead to the scenario where node operators could edit this constant value, then rebuild their binary and return an incorrect value for this query. Since the value is not stored in the app state (db), there is no check being done between nodes, meaning they could all have different values.
I suggest we set this value in the KVStore, but not as a param. This way it is included in the AppHash, so validators who change this value, will have an Consensus error. Not setting it as a param means we can also not expose any way for the value to be edited programmatically.
Thoughts?

That sounds fair. I don't see downside, we just need to keep the stateless share verification methods we had so far
