### ISSUE TITLE
Vouchers transfers disabled during simulation

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#719]
To reproduce: use `seed=55` with ` make test-sim-ci`

It seems simulation of `SimulateMsgSendVouchers` (that is never simulated for most seed: https://github.com/tendermint/spn/issues/358) fails with the following error

```
Simulating... block 3/200, operation 0/40.--- FAIL: BenchmarkSimulation
    simulate.go:300: error on block  3/200, operation (26/97) from x/campaign:
        failed to execute message; message index: 0: v/3/bar transfers are currently disabled: send transactions are disabled [cosmos/cosmos-sdk@v0.45.2/x/bank/keeper/send.go:275]
        Comment: unable to deliver tx
```

We should ensure this error doesn't imply something wrong with voucher coins that can be reproduced outside of simulations

**Comment by giunatale** [comment]
are we messing with the `send_enabled` flag for denoms in `bank`? This AFAIK is the cause for such error.

**Comment by giunatale** [comment]
Actually, from what it seems `send_enabled` seems to be globally set to `false`

**Comment by lubtd** [comment]
Ok I wasn't aware of such a flag since we can send the voucher with no problem with a local testnet

**Comment by giunatale** [comment]
So I guess we have a couple options here:
we either override the randomized `default_send_enabled` and `send_enabled` params for `bank` in `CustomAppStateFn` (`app/simutil/app_state.go`) or we prevent doing send operations if those are set to prevent transfers.

However, the latter solution seems unfitting for our case since we would never have scenario where we disable transfers, I believe.
Thoughts?
