### ISSUE TITLE
Create a query to show a list of fundraiser IDs associated with a particular campaign ID

### ISSUE THREAD

**Issue by fadeev** [tendermint/spn#756]

**Comment by lubtd** [comment]
This is one we could try with events
Fetching `EventTypeCreateFixedPriceAuction ` https://github.com/tendermint/fundraising/blob/7524ab763e18891752ddddf03bdc69d38791a8c4/x/fundraising/keeper/auction.go#L83
Where
`AttributeKeyAuctioneerAddress ` contains the coordinator address
`AttributeKeySellingCoin` contains `v/{campaignID}/` since the format of a voucher denom is `v/{campaignID}/{tokenDenom}`

**Comment by fadeev** [comment]
This is the closest I can get right now:

https://rpc.nightly.starport.network/tx_search?query=%22message.action=%27create_fixed_price_auction%27%20AND%20create_fixed_price_auction.selling_coin=%275000v/4/bar%27%22

This obviously doesn't do the job, because we're using `=`, not `contains`, but I can't get `contains` to work. This should work, but it doesn't:

https://rpc.nightly.starport.network/tx_search?query=%22message.action=%27create_fixed_price_auction%27%20AND%20create_fixed_price_auction.selling_coin%20CONTAINS%20%27v/4%27%22

**Comment by lubtd** [comment]
`CONTAINS` works for the auctioneer address
https://rpc.nightly.starport.network/tx_search?query=%22message.action=%27create_fixed_price_auction%27%20AND%20create_fixed_price_auction.auctioneer_address%20CONTAINS%20%27spn1mceyc6styw09gaa4saxfmz75camnpd7vumjywl%27%22

**Comment by lubtd** [comment]
I don't clearly get the origin of the issue for the auction selling coins. Maybe it's because `selling_coins` is a coin object at first but it is normally represented through a string in the event

But if we can search for addresses we can at least in theory retrieve:
- chains from a validator address
- chains, campaigns from a coordinator address

And we do a custom query for the fundraisers

**Comment by lubtd** [comment]
I will refactor `launch` events in order to be able to parse addresses

**Comment by fadeev** [comment]
> And we do a custom query for the fundraisers

@lubtd To keep this issue scoped to a particular frontend requirement, you're saying that to get a list of fundraisers that belong to a specific campaign, we need to create a new query, right? Just making sure.

**Comment by lubtd** [comment]
Yes, creating a new query, unless we find out the issue with `CONTAINS`

> I will refactor launch events in order to be able to parse addresses

Is not related to this issue

**Comment by giunatale** [comment]
Do we really want to use the format of the `sellingCoin` to get the campaign ID? What if the auctioned token is not a voucher?

Using the auctioneer address is also problematic, since coordinators can be updated. So if I use the auctioneer address to find the coordinator I may not find the right coordinator. On top of that, coordinators can create multiple campaigns.

I think this is trickier than it seems. Might require to explicitly associate auctions with campaigns on-chain. An indirect association is prone to errors due to what's written above.

Thoughts?

**Comment by fadeev** [comment]
A fundraiser may or may not belong to a campaign. I think getting that info from a denom is fine, because if a denom is a voucher, we get the campaign ID. If it's not, we return that the campaign ID for this fundraiser is `false`, 0 or whatever.
