### ISSUE TITLE
Investigate and discuss additional mechanism for `DeveloperFund`

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#840]
Explore additional mechanism related to `DeveloperFund` distribution in the `mint` module like locking the funds for a specific delay or performing periodic distribution

**Comment by giunatale** [comment]
Perhaps handling development funding through a separate module might be the solution. Funds could be locked using a custom schedule there and unlocked gradually. Admittedly one could argue that since block rewards are relatively small, the way funds are disbursed for development is already "gradual" and on a per-block basis. So perhaps there might be no need for this. I guess this is just a matter of making this development funding air tight to ensure fairness and

**Comment by lubtd** [comment]
Why would you consider a secondary module and not using `mint` module account?

**Comment by lubtd** [comment]
Moved in https://github.com/ignite/modules/issues/22
