### ISSUE TITLE
feature(grpc): improve proposal querying

### ISSUE THREAD

**Issue by ilgooz** [tendermint/spn#85]
* 1st: Merging [PendingProposals,  ApprovedProposals and RejectedProposals](https://github.com/tendermint/spn/blob/1e20634/proto/genesis/v1beta/querier.proto#L13-L15) into one `Proposals` function by having a _Status_ filtering option within `QueryProposalsRequest`(new). When this filter isn't provided, all proposals for the chain can be returned. Meanwhile we need to enable pagination.

* 2nd: Add `Type` filtering option to _QueryProposalsRequest_ so we can filter proposals by their type(validator/account). Useful for [this](https://github.com/tendermint/starport/issues/479#issuecomment-737815586).

* 3rd: Add another RPC func called `CountProposals` that accepts the same `QueryProposalsRequest` but instead it returns the count. Useful to implement [this](https://github.com/tendermint/starport/issues/479#issuecomment-737815586).

Overall it should look like:
```proto
rpc Proposals(QueryProposalsRequest) returns (QueryProposalsResponse);
rpc CountProposals(QueryProposalsRequest) returns (QueryCountProposalsResponse);
```

```proto
message QueryProposalsRequest {
    string chainID = 1;
    Status status = 2;
    Type type = 3; // new field: can be one of account, validator, change
    cosmos.base.query.v1beta1.PageResponse pagination = 1;
}

message QueryProposalsResponse {
    repeated Proposal proposals = 1;
    cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

message QueryCountProposalsResponse {
    int64 count = 1;
}
```

What are your thoughts on these?

**Comment by ltacker** [comment]
> 1st: Merging PendingProposals, ApprovedProposals and RejectedProposals into one Proposals function by having a Status filtering option within QueryProposalsRequest(new). When this filter isn't provided, all proposals for the chain can be returned. Meanwhile we need to enable pagination.

We have currently the list of proposal IDs stored by their status in the store of the chain so that's why the queries were separated by the status.
We have this architecture initially to be more efficient because, for example, to verify if a validator can be added, we needed to check if the account existed by going through all the approved proposals. Actually, we are not using this method anymore to verify existing account for adding validators. So we may even check if we could do a refactoring and removing this entire structure in the store. (We can still now implement `Proposals()` by querying proposals from each of the 3 status dependent queries)

> 2nd: Add Type filtering option to QueryProposalsRequest so we can filter proposals by their type(validator/account). Useful for this.

> 3rd: Add another RPC func called CountProposals that accepts the same QueryProposalsRequest but instead it returns the count. Useful to implement this.

Both of them are good for me

**Comment by ilgooz** [comment]
Sounds great :guitar:

**Comment by ltacker** [comment]
So it's actually very likely that we will not need the approved/pending/rejected pools anymore since we removed genesis stateful logic from `spn`. For a specific check if a proposal can be approved we can create a specific structure in the store like the `account` store to check if an account already exists

**Comment by ltacker** [comment]
Proposal indexed by status is still necessary for `LaunchInformation()` query. To have a deterministic way to construct the Launch Information we must store the order in which the proposals have been approved.

But I also think implementing `Proposal()` by calling `ApprovedProposal()`, `PendingProposal()` and then `RejectedProposal()` could be good in a UX point of view in the sense that we would display first all the approved proposals in the order they were approved, then the pending ones and then the rejected ones. What do you think of this @ilgooz ?

**Comment by ilgooz** [comment]
Merging approved, pending and rejected proposals seems good to me. :+1:
