### ISSUE TITLE
Publish with genesis file bufio.Scanner: token too long

### ISSUE THREAD

**Issue by silverstr89** [tendermint/spn#980]
When i trying 

ignite n chain publish https://github.com/silverstr89/alexey-cosmos.git --genesis "https://github.com/silverstr89/alexey-cosmos/blob/master/genesis.json" --local

```
✔ Source code fetched
✔ Blockchain set up
✔ Chain's binary built
✔ Blockchain initialized
✔ Custom Genesis JSON from URL fetched
```

i got error
bufio.Scanner: token too long

how can i fix?

you could also check my repo and genesis for reproducing

https://github.com/silverstr89/alexey-cosmos

https://github.com/silverstr89/alexey-cosmos/blob/master/genesis.json

**Comment by silverstr89** [comment]
@lubtd is it possible to run it from local genesis file?

**Comment by lubtd** [comment]
> @lubtd is it possible to run it from local genesis file?

This is in progress: https://github.com/ignite/cli/issues/2852

It will be possible to specify for the initial genesis of the chain the genesis state defined in a config yml file in the project repo

**Comment by silverstr89** [comment]
ah... ok... will wait when it will be possible to use --genesis-config config.yml

**Comment by lubtd** [comment]
@silverstr89 for the original issue:
The provided URL for genesis in the example contains the HTLM page showing the genesis so the parsing will fail. You must provide the raw content of the genesis: https://raw.githubusercontent.com/silverstr89/alexey-cosmos/master/genesis.json
Though the error is not self-explanatory, we should print something like `invalid JSON file`

When providing the raw content, it will still fail because:
- We for now don't allow having existing gentxs in the genesis, the genesis should not have gentxs, then gentxs are added with Genesis Validators requests on the Ignite Chain
- The chain ID in the genesis `alexey` is not supported, we currently only support chain ID with the format `<name>-<number>` but the flag `--chain-id` allow to specify a custom chain ID for the chain during publish

So the following command works for publishing the chain:
```
ignite n chain publish https://github.com/silverstr89/alexey-cosmos.git --genesis "https://gist.githubusercontent.com/lubtd/f2144f19ae03f0d7c1519fc0edc6d1fd/raw/5d16f1a957fdd379b58fecab82c0cec1f2381d50/genesis-a.json" --chain-id alexey-0
```

**Comment by silverstr89** [comment]
@lubtd thank you so much!
